### ISSUE TITLE
name 'std' is not defined (index funds perfomance notebook)

### ISSUE THREAD

**Issue by dknugo** [mbk-dev/okama#2] opened 2020-12-06 08:17 UTC
sp.index_beta.plot() call terminates with this error:
NameError: name 'std' is not defined

**Comment by chilango74** [comment] 2020-12-06 08:47
@dknugo Thanks for feedback. I know about this bug. Next week we are planning a release with several fixes and new instruments for distributions.

**Comment by chilango74** [comment] 2020-12-08 05:58
New lelease covering the issue is out. Closing ...

**Closed by chilango74** 2020-12-08 05:58 UTC
